    {
        "type": "Feature",
        "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
                [
                    [
                        [
                            -8.488007362,
                            40.200175615
                        ],
                        [
                            -8.488010055,
                            40.200184574
                        ],
                        [
                            -8.488012753,
                            40.200193532
                        ],
                        [
                            -8.48797935,
                            40.200199154
                        ],
                        [
                            -8.487981817,
                            40.200189308
                        ],
                        [
                            -8.487982669,
                            40.200179738
                        ],
                        [
                            -8.488007362,
                            40.200175615
                        ]
                    ]
                ]
            ]
        },
        "properties": {
            "ae": "A1",
            "fk_sublanco": "11e739c9-74d9-4a8b-983b-201cd6d2a04c",
            "fk_sublanco_descr": "Coimbra Sul-Coimbra Norte (A1/A14)",
            "classe_num": "Berma entre 2 metros e 2.5 metros",
            "class_berm": "Berma Intermédia",
            "sentido": "Crescente",
            "pk_inicio": 189292.0,
            "pk_fim": 189294.0,
            "id": "a5ff9484-3913-4a3a-a7e0-28338a5e5632"
        },
        "id": "a5ff9484-3913-4a3a-a7e0-28338a5e5632",
        "prev": "a5ff9078-832c-41fd-9647-61db43ea333f",
        "next": "a60060fa-a467-4dfa-b751-960cf77bbdde",
        "links": [
            {
                "type": "application/json",
                "rel": "root",
                "title": "The landing page of this server as JSON",
                "href": "https://apibrisa.niugis.com?f=json"
            },
            {
                "type": "text/html",
                "rel": "root",
                "title": "The landing page of this server as HTML",
                "href": "https://apibrisa.niugis.com?f=html"
            },
            {
                "rel": "self",
                "type": "application/geo+json",
                "title": "This document as GeoJSON",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr/items/a5ff9484-3913-4a3a-a7e0-28338a5e5632?f=json"
            },
            {
                "rel": "alternate",
                "type": "application/ld+json",
                "title": "This document as RDF (JSON-LD)",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr/items/a5ff9484-3913-4a3a-a7e0-28338a5e5632?f=jsonld"
            },
            {
                "rel": "alternate",
                "type": "text/html",
                "title": "This document as HTML",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr/items/a5ff9484-3913-4a3a-a7e0-28338a5e5632?f=html"
            },
            {
                "rel": "collection",
                "type": "application/json",
                "title": "Zonas de paragem bcr",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr"
            },
            {
                "rel": "prev",
                "type": "application/json",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr/items/a5ff9078-832c-41fd-9647-61db43ea333f?f=json"
            },
            {
                "rel": "next",
                "type": "application/json",
                "href": "https://apibrisa.niugis.com/collections/zonas_de_paragem_bcr/items/a60060fa-a467-4dfa-b751-960cf77bbdde?f=json"
            }
        ]
    }
