#%RAML 1.0 DataType 
type: object
properties:
  type:
    type: string
    example: FeatureCollection
    required: false
  features:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
          example: Feature
          required: false
        geometry:
          type: object
          properties:
            type:
              type: string
              example: MultiPolygon
              required: false
            coordinates:
              type: array
              items:
                type: array
        properties:
          type: object
          properties:
            ae_fk:
              type: string
              example: 0aa52682-cbeb-4547-b5b8-a4afab615b83
              required: false
            ae_fk_descr:
              type: string
              example: A5 - Auto-Estrada da Costa do Estoril
              required: false
            fk_no:
              type: string
              example: 483bb9c0-3e83-47c8-aab0-9d5b3b7eaab9
              required: false
            fk_no_descr:
              type: string
              example: Estoril
              required: false
            designa_concat:
              type: string
              example: Portagem Estoril
              required: false
            designa:
              type: string
              example: Estoril
              required: false
            n_barreira:
              type: string
              example: '0506'
              required: false
            sublanco:
              type: string
              example: Carcavelos - Estoril
              required: false
            sentido:
              type: string
              example: Decrescente
              required: false
            posicao:
              type: 'null'
              example: null
              required: false
            km_inicial:
              type: number
              example: 19.7
              required: false
            pv_no:
              type: string
              example: Nó
              required: false
            ramo:
              type: string
              example: E+F
              required: false
            tipo_zona:
              type: string
              example: Portagem de Nó
              required: false
            cen_operac:
              type: string
              example: CO-Carcavelos/Loures
              required: false
            n_ilhas:
              type: string
              example: '5'
              required: false
            n_vias:
              type: string
              example: '6'
              required: false
            n_cabines:
              type: string
              example: '4'
              required: false
            data_da_ultima_actualizacao:
              type: datetime-only
              example: '2023-08-01T11:39:54'
              required: false
            id:
              type: string
              example: 51650dd7-ca01-47ab-bc1a-e75b478c6be5
              required: false
        id:
          type: string
          example: 51650dd7-ca01-47ab-bc1a-e75b478c6be5
          required: false
  links:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
          example: application/geo+json
          required: false
        rel:
          type: string
          example: self
          required: false
        title:
          type: string
          example: This document as GeoJSON
          required: false
        href:
          type: string
          example: >-
            https://apibrisa.niugis.com/collections/barreiras_de_portagem/items?f=json
          required: false
  timeStamp:
    type: string
    example: '2024-04-09T16:23:40.028244Z'
    required: false
  
 